# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’

use_frameworks!

def app_pods
    pod 'ModesoWheel', :path => '../'
end

target 'ModesoWheelDemo' do
    app_pods
end
